/**
 * @file regions.ts
 * @description Static database of major cloud provider regions, geographic coordinates,
 * and regional endpoints used for latency testing.
 */

export interface Region {
  id: string;
  provider: "aws" | "gcp" | "azure";
  name: string;
  lat: number;
  lon: number;
  pingUrl: string;
  baseLatency: number; // fallback latency in ms if network fails
}

/**
 * list of major global cloud regions for latency tracking.
 * coordinates are mapped to latitude and longitude.
 * ping urls point to regional service endpoints or status endpoints.
 */
export const REGIONS: Region[] = [
  // AWS Regions
  {
    id: "us-east-1",
    provider: "aws",
    name: "AWS US East (N. Virginia)",
    lat: 39.0438,
    lon: -77.4874,
    pingUrl: "https://dynamodb.us-east-1.amazonaws.com",
    baseLatency: 15,
  },
  {
    id: "us-west-2",
    provider: "aws",
    name: "AWS US West (Oregon)",
    lat: 45.7285,
    lon: -120.2401,
    pingUrl: "https://dynamodb.us-west-2.amazonaws.com",
    baseLatency: 35,
  },
  {
    id: "eu-west-1",
    provider: "aws",
    name: "AWS Europe (Ireland)",
    lat: 53.3498,
    lon: -6.2603,
    pingUrl: "https://dynamodb.eu-west-1.amazonaws.com",
    baseLatency: 95,
  },
  {
    id: "eu-central-1",
    provider: "aws",
    name: "AWS Europe (Frankfurt)",
    lat: 50.1109,
    lon: 8.6821,
    pingUrl: "https://dynamodb.eu-central-1.amazonaws.com",
    baseLatency: 105,
  },
  {
    id: "ap-northeast-1",
    provider: "aws",
    name: "AWS Asia Pacific (Tokyo)",
    lat: 35.6762,
    lon: 139.6503,
    pingUrl: "https://dynamodb.ap-northeast-1.amazonaws.com",
    baseLatency: 180,
  },
  {
    id: "ap-southeast-1",
    provider: "aws",
    name: "AWS Asia Pacific (Singapore)",
    lat: 1.3521,
    lon: 103.8198,
    pingUrl: "https://dynamodb.ap-southeast-1.amazonaws.com",
    baseLatency: 220,
  },
  {
    id: "ap-southeast-2",
    provider: "aws",
    name: "AWS Asia Pacific (Sydney)",
    lat: -33.8688,
    lon: 151.2093,
    pingUrl: "https://dynamodb.ap-southeast-2.amazonaws.com",
    baseLatency: 240,
  },
  {
    id: "sa-east-1",
    provider: "aws",
    name: "AWS South America (São Paulo)",
    lat: -23.5505,
    lon: -46.6333,
    pingUrl: "https://dynamodb.sa-east-1.amazonaws.com",
    baseLatency: 160,
  },
  {
    id: "af-south-1",
    provider: "aws",
    name: "AWS Africa (Cape Town)",
    lat: -33.9249,
    lon: 18.4241,
    pingUrl: "https://dynamodb.af-south-1.amazonaws.com",
    baseLatency: 260,
  },
  {
    id: "me-central-1",
    provider: "aws",
    name: "AWS Middle East (UAE)",
    lat: 24.4539,
    lon: 54.3773,
    pingUrl: "https://dynamodb.me-central-1.amazonaws.com",
    baseLatency: 230,
  },

  // GCP Regions
  {
    id: "us-east1",
    provider: "gcp",
    name: "GCP US East (South Carolina)",
    lat: 33.8361,
    lon: -81.1637,
    pingUrl: "https://us-east1-ping.gstatic.com/ping",
    baseLatency: 25,
  },
  {
    id: "us-central1",
    provider: "gcp",
    name: "GCP US Central (Iowa)",
    lat: 41.2619,
    lon: -95.8447,
    pingUrl: "https://us-central1-ping.gstatic.com/ping",
    baseLatency: 30,
  },
  {
    id: "us-west1",
    provider: "gcp",
    name: "GCP US West (Oregon)",
    lat: 45.7285,
    lon: -120.2401,
    pingUrl: "https://us-west1-ping.gstatic.com/ping",
    baseLatency: 40,
  },
  {
    id: "europe-west1",
    provider: "gcp",
    name: "GCP Europe (Belgium)",
    lat: 50.8503,
    lon: 4.3517,
    pingUrl: "https://europe-west1-ping.gstatic.com/ping",
    baseLatency: 100,
  },
  {
    id: "europe-west3",
    provider: "gcp",
    name: "GCP Europe (Frankfurt)",
    lat: 50.1109,
    lon: 8.6821,
    pingUrl: "https://europe-west3-ping.gstatic.com/ping",
    baseLatency: 110,
  },
  {
    id: "asia-east1",
    provider: "gcp",
    name: "GCP Asia East (Taiwan)",
    lat: 24.0000,
    lon: 121.0000,
    pingUrl: "https://asia-east1-ping.gstatic.com/ping",
    baseLatency: 190,
  },
  {
    id: "asia-northeast1",
    provider: "gcp",
    name: "GCP Asia Northeast (Tokyo)",
    lat: 35.6762,
    lon: 139.6503,
    pingUrl: "https://asia-northeast1-ping.gstatic.com/ping",
    baseLatency: 185,
  },
  {
    id: "asia-southeast1",
    provider: "gcp",
    name: "GCP Asia Southeast (Singapore)",
    lat: 1.3521,
    lon: 103.8198,
    pingUrl: "https://asia-southeast1-ping.gstatic.com/ping",
    baseLatency: 225,
  },
  {
    id: "australia-southeast1",
    provider: "gcp",
    name: "GCP Australia Southeast (Sydney)",
    lat: -33.8688,
    lon: 151.2093,
    pingUrl: "https://australia-southeast1-ping.gstatic.com/ping",
    baseLatency: 245,
  },
  {
    id: "southamerica-east1",
    provider: "gcp",
    name: "GCP South America (São Paulo)",
    lat: -23.5505,
    lon: -46.6333,
    pingUrl: "https://southamerica-east1-ping.gstatic.com/ping",
    baseLatency: 165,
  },

  // Azure Regions
  {
    id: "eastus",
    provider: "azure",
    name: "Azure US East (Virginia)",
    lat: 39.0438,
    lon: -77.4874,
    pingUrl: "https://eastus.blob.core.windows.net",
    baseLatency: 18,
  },
  {
    id: "westus2",
    provider: "azure",
    name: "Azure US West (Washington)",
    lat: 47.6062,
    lon: -122.3321,
    pingUrl: "https://westus2.blob.core.windows.net",
    baseLatency: 45,
  },
  {
    id: "northeurope",
    provider: "azure",
    name: "Azure Europe North (Ireland)",
    lat: 53.3498,
    lon: -6.2603,
    pingUrl: "https://northeurope.blob.core.windows.net",
    baseLatency: 98,
  },
  {
    id: "westeurope",
    provider: "azure",
    name: "Azure Europe West (Netherlands)",
    lat: 52.3676,
    lon: 4.9041,
    pingUrl: "https://westeurope.blob.core.windows.net",
    baseLatency: 102,
  },
  {
    id: "japaneast",
    provider: "azure",
    name: "Azure Japan East (Tokyo)",
    lat: 35.6762,
    lon: 139.6503,
    pingUrl: "https://japaneast.blob.core.windows.net",
    baseLatency: 182,
  },
  {
    id: "southeastasia",
    provider: "azure",
    name: "Azure Southeast Asia (Singapore)",
    lat: 1.3521,
    lon: 103.8198,
    pingUrl: "https://southeastasia.blob.core.windows.net",
    baseLatency: 222,
  },
  {
    id: "australiaeast",
    provider: "azure",
    name: "Azure Australia East (Sydney)",
    lat: -33.8688,
    lon: 151.2093,
    pingUrl: "https://australiaeast.blob.core.windows.net",
    baseLatency: 242,
  },
  {
    id: "brazilsouth",
    provider: "azure",
    name: "Azure Brazil South (São Paulo)",
    lat: -23.5505,
    lon: -46.6333,
    pingUrl: "https://brazilsouth.blob.core.windows.net",
    baseLatency: 162,
  },
  {
    id: "southafricanorth",
    provider: "azure",
    name: "Azure South Africa North (Johannesburg)",
    lat: -26.2041,
    lon: 28.0473,
    pingUrl: "https://southafricanorth.blob.core.windows.net",
    baseLatency: 255,
  },
];
